language: java

jdk:
  - oraclejdk7

env:
  global:
    - secure: fDUH31GtDiN1FV5plwzkIV8+stMYzJwc14XCT/R+IpE/mWutFpBh3bXhijeo0mR6xFg9k1kKgUtslLL19CM3NH1ewsWJ7AkAeIBT7gw7UotW+A0Yi8GIiWPjrDroILbf973LhkKSSP7l3L7Nx+DSapCjqSrfgUB5wVnBca0wL1I=
    - secure: k8Ei5bNj+FxMX1Utdkj+AoyuiHah5NMj76OGYr7r8cdII1GoD+rLcTYcSH1r6w1KRktBzFPcCUdnlg8QSnER5NF/7GSa/yNXglDizs6pS8lkDWMlB1v2oGJsD+GkGsQiAcxMgjMwUijxMiWFS1Pb6Gp+L7824VVTJERktMrp0vk=
    - TERM=dumb

after_success:
  - gradle coverage coveralls
  - .scripts/publish-to-sonatype.sh